<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260811174112 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE berth_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, berth_id INT NOT NULL, boat_id INT NOT NULL, requester_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5822A60F34832E6 ON berth_requests (berth_id)');
        $this->addSql('CREATE INDEX IDX_5822A60FA1E84A29 ON berth_requests (boat_id)');
        $this->addSql('CREATE INDEX IDX_5822A60FED442CF4 ON berth_requests (requester_id)');
        $this->addSql('ALTER TABLE berth_requests ADD CONSTRAINT FK_5822A60F34832E6 FOREIGN KEY (berth_id) REFERENCES berths (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE berth_requests ADD CONSTRAINT FK_5822A60FA1E84A29 FOREIGN KEY (boat_id) REFERENCES boats (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE berth_requests ADD CONSTRAINT FK_5822A60FED442CF4 FOREIGN KEY (requester_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE berth_requests DROP CONSTRAINT FK_5822A60F34832E6');
        $this->addSql('ALTER TABLE berth_requests DROP CONSTRAINT FK_5822A60FA1E84A29');
        $this->addSql('ALTER TABLE berth_requests DROP CONSTRAINT FK_5822A60FED442CF4');
        $this->addSql('DROP TABLE berth_requests');
    }
}
