<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260721122244 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE signalements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message VARCHAR(2000) NOT NULL, reponse_admin VARCHAR(2000) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reservation_id INT NOT NULL, auteur_id INT NOT NULL, repondant_admin_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_120AE27B83297E7 ON signalements (reservation_id)');
        $this->addSql('CREATE INDEX IDX_120AE2760BB6FE6 ON signalements (auteur_id)');
        $this->addSql('CREATE INDEX IDX_120AE278E25BF67 ON signalements (repondant_admin_id)');
        $this->addSql('ALTER TABLE signalements ADD CONSTRAINT FK_120AE27B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalements ADD CONSTRAINT FK_120AE2760BB6FE6 FOREIGN KEY (auteur_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalements ADD CONSTRAINT FK_120AE278E25BF67 FOREIGN KEY (repondant_admin_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql("ALTER TABLE notifications ADD type VARCHAR(30) NOT NULL DEFAULT 'RGPD_SUPPRESSION'");
        $this->addSql('ALTER TABLE notifications ALTER COLUMN type DROP DEFAULT');
        $this->addSql('ALTER TABLE notifications ADD reservation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservations (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6000B0D3B83297E7 ON notifications (reservation_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE signalements DROP CONSTRAINT FK_120AE27B83297E7');
        $this->addSql('ALTER TABLE signalements DROP CONSTRAINT FK_120AE2760BB6FE6');
        $this->addSql('ALTER TABLE signalements DROP CONSTRAINT FK_120AE278E25BF67');
        $this->addSql('DROP TABLE signalements');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3B83297E7');
        $this->addSql('DROP INDEX IDX_6000B0D3B83297E7');
        $this->addSql('ALTER TABLE notifications DROP type');
        $this->addSql('ALTER TABLE notifications DROP reservation_id');
    }
}
