<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260720145247 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'BE-14 : ajoute matricule/description/photoUrl à boats et crée la table repairs (historique des réparations).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE repairs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(2000) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, boat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57E93B61A1E84A29 ON repairs (boat_id)');
        $this->addSql('ALTER TABLE repairs ADD CONSTRAINT FK_57E93B61A1E84A29 FOREIGN KEY (boat_id) REFERENCES boats (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boats ADD matricule VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE boats ADD description VARCHAR(2000) DEFAULT NULL');
        $this->addSql('ALTER TABLE boats ADD photo_url VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8DDF090612B2DC9C ON boats (matricule)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE repairs DROP CONSTRAINT FK_57E93B61A1E84A29');
        $this->addSql('DROP TABLE repairs');
        $this->addSql('DROP INDEX UNIQ_8DDF090612B2DC9C');
        $this->addSql('ALTER TABLE boats DROP matricule');
        $this->addSql('ALTER TABLE boats DROP description');
        $this->addSql('ALTER TABLE boats DROP photo_url');
    }
}
