<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260720170855 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'BE-15 : crée la table reservations (réservations/locations de bateaux).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reservations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, boat_id INT NOT NULL, renter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4DA239A1E84A29 ON reservations (boat_id)');
        $this->addSql('CREATE INDEX IDX_4DA239E289A545 ON reservations (renter_id)');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA239A1E84A29 FOREIGN KEY (boat_id) REFERENCES boats (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA239E289A545 FOREIGN KEY (renter_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA239A1E84A29');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA239E289A545');
        $this->addSql('DROP TABLE reservations');
    }
}
