<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704200641 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE boats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, port_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8DDF09067E3C61F9 ON boats (owner_id)');
        $this->addSql('CREATE INDEX IDX_8DDF090676E92A9C ON boats (port_id)');
        $this->addSql('CREATE TABLE log_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrival_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, distance_nm DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, boat_id INT NOT NULL, departure_port_id INT NOT NULL, arrival_port_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15358B52A1E84A29 ON log_entries (boat_id)');
        $this->addSql('CREATE INDEX IDX_15358B526CCE6D2D ON log_entries (departure_port_id)');
        $this->addSql('CREATE INDEX IDX_15358B52BD22E494 ON log_entries (arrival_port_id)');
        $this->addSql('CREATE TABLE ports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, city VARCHAR(100) NOT NULL, latitude NUMERIC(10, 7) NOT NULL, longitude NUMERIC(10, 7) NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, license_number VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE boats ADD CONSTRAINT FK_8DDF09067E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE boats ADD CONSTRAINT FK_8DDF090676E92A9C FOREIGN KEY (port_id) REFERENCES ports (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE log_entries ADD CONSTRAINT FK_15358B52A1E84A29 FOREIGN KEY (boat_id) REFERENCES boats (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE log_entries ADD CONSTRAINT FK_15358B526CCE6D2D FOREIGN KEY (departure_port_id) REFERENCES ports (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE log_entries ADD CONSTRAINT FK_15358B52BD22E494 FOREIGN KEY (arrival_port_id) REFERENCES ports (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE boats DROP CONSTRAINT FK_8DDF09067E3C61F9');
        $this->addSql('ALTER TABLE boats DROP CONSTRAINT FK_8DDF090676E92A9C');
        $this->addSql('ALTER TABLE log_entries DROP CONSTRAINT FK_15358B52A1E84A29');
        $this->addSql('ALTER TABLE log_entries DROP CONSTRAINT FK_15358B526CCE6D2D');
        $this->addSql('ALTER TABLE log_entries DROP CONSTRAINT FK_15358B52BD22E494');
        $this->addSql('DROP TABLE boats');
        $this->addSql('DROP TABLE log_entries');
        $this->addSql('DROP TABLE ports');
        $this->addSql('DROP TABLE users');
    }
}
