<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260813112435 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Suppression de la table log_entries (retrait du Smart LogBook / Trajets).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE log_entries DROP CONSTRAINT fk_15358b52a1e84a29');
        $this->addSql('ALTER TABLE log_entries DROP CONSTRAINT fk_15358b526cce6d2d');
        $this->addSql('ALTER TABLE log_entries DROP CONSTRAINT fk_15358b52bd22e494');
        $this->addSql('DROP TABLE log_entries');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE log_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrival_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, distance_nm DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, boat_id INT NOT NULL, departure_port_id INT NOT NULL, arrival_port_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_15358b52bd22e494 ON log_entries (arrival_port_id)');
        $this->addSql('CREATE INDEX idx_15358b52a1e84a29 ON log_entries (boat_id)');
        $this->addSql('CREATE INDEX idx_15358b526cce6d2d ON log_entries (departure_port_id)');
        $this->addSql('ALTER TABLE log_entries ADD CONSTRAINT fk_15358b52a1e84a29 FOREIGN KEY (boat_id) REFERENCES boats (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_entries ADD CONSTRAINT fk_15358b526cce6d2d FOREIGN KEY (departure_port_id) REFERENCES ports (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log_entries ADD CONSTRAINT fk_15358b52bd22e494 FOREIGN KEY (arrival_port_id) REFERENCES ports (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
