<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260720155634 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'BE-16 : crée la table berths (emplacements précis des bateaux dans les ports).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE berths (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(50) NOT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, port_id INT NOT NULL, boat_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_53CA9E7D76E92A9C ON berths (port_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53CA9E7DA1E84A29 ON berths (boat_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_port_label ON berths (port_id, label)');
        $this->addSql('ALTER TABLE berths ADD CONSTRAINT FK_53CA9E7D76E92A9C FOREIGN KEY (port_id) REFERENCES ports (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE berths ADD CONSTRAINT FK_53CA9E7DA1E84A29 FOREIGN KEY (boat_id) REFERENCES boats (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE berths DROP CONSTRAINT FK_53CA9E7D76E92A9C');
        $this->addSql('ALTER TABLE berths DROP CONSTRAINT FK_53CA9E7DA1E84A29');
        $this->addSql('DROP TABLE berths');
    }
}
