server {
    listen 80;
    server_name nautilog.fr www.nautilog.fr;

    server_tokens off;

    resolver 127.0.0.11 valid=10s;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        set $client_upstream client:80;
        proxy_pass http://$client_upstream;
        proxy_set_header Host $host;
    }

    location /uploads {
        alias /var/www/api/public/uploads;
        add_header Cache-Control "public, max-age=3600";
    }

    location /api {
        root /var/www/api/public;
        rewrite ^/api(/.*)?$ /index.php break;

        fastcgi_pass api:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        include fastcgi_params;
    }
}
